source 'https://rubygems.org'
# Public gems from RubyGems:
gem 'bundler-audit', '~> 0.9', require: false
gem 'chutney', '~> 3.9', require: false
gem 'config', '~> 5.5'
gem 'cucumber', '~> 9.2'
gem 'dvla-herodotus', '~> 2.0'
gem 'dvla-lint', '~> 1.8', require: false
gem 'faker', '~> 3.5'
gem 'faker_maker', '~> 2.1'
gem 'hash_miner', '~> 1.1'
gem 'httparty', '~> 0.22'
gem 'parallel_tests', '~> 4.7', require: false
gem 'rake', '~> 13.2'
gem 'rspec-expectations', '~> 3.13'
gem 'simple_symbolize', '~> 4.0'
